detectors:
  TooManyStatements:
    max_statements: 8

  DuplicateMethodCall:
    exclude:
      - PopularRoutes#query
      - Visits#group_by

  FeatureEnvy:
    exclude:
      - PopularRoutes#query
      - Visits#group_by

  UtilityFunction:
    exclude:
      - RevisitedRoutes#revisited_visitors
